package clasesHibernate;

// Generated 30-nov-2015 12:27:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ofertaeducativa generated by hbm2java
 */
public class Ofertaeducativa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String codOe;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Set<Curso> cursos = new HashSet<Curso>(0);

	public Ofertaeducativa() {
	}

	public Ofertaeducativa(String codOe) {
		this.codOe = codOe;
	}

	public Ofertaeducativa(String codOe, String nombre, String descripcion,
			String tipo, Set<Curso> cursos) {
		this.codOe = codOe;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.cursos = cursos;
	}

	public String getCodOe() {
		return this.codOe;
	}

	public void setCodOe(String codOe) {
		this.codOe = codOe;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(Set<Curso> cursos) {
		this.cursos = cursos;
	}

}
