package clasesHibernate;

// Generated 18-nov-2015 12:47:59 by Hibernate Tools 3.4.0.CR1

/**
 * HorarioId generated by hbm2java
 */
public class HorarioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codOe;
	private String codCurso;
	private String codAsignatura;
	private String codTramo;

	public HorarioId() {
	}

	public HorarioId(String codOe, String codCurso, String codAsignatura,
			String codTramo) {
		this.codOe = codOe;
		this.codCurso = codCurso;
		this.codAsignatura = codAsignatura;
		this.codTramo = codTramo;
	}

	public String getCodOe() {
		return this.codOe;
	}

	public void setCodOe(String codOe) {
		this.codOe = codOe;
	}

	public String getCodCurso() {
		return this.codCurso;
	}

	public void setCodCurso(String codCurso) {
		this.codCurso = codCurso;
	}

	public String getCodAsignatura() {
		return this.codAsignatura;
	}

	public void setCodAsignatura(String codAsignatura) {
		this.codAsignatura = codAsignatura;
	}

	public String getCodTramo() {
		return this.codTramo;
	}

	public void setCodTramo(String codTramo) {
		this.codTramo = codTramo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HorarioId))
			return false;
		HorarioId castOther = (HorarioId) other;

		return ((this.getCodOe() == castOther.getCodOe()) || (this.getCodOe() != null
				&& castOther.getCodOe() != null && this.getCodOe().equals(
				castOther.getCodOe())))
				&& ((this.getCodCurso() == castOther.getCodCurso()) || (this
						.getCodCurso() != null
						&& castOther.getCodCurso() != null && this
						.getCodCurso().equals(castOther.getCodCurso())))
				&& ((this.getCodAsignatura() == castOther.getCodAsignatura()) || (this
						.getCodAsignatura() != null
						&& castOther.getCodAsignatura() != null && this
						.getCodAsignatura()
						.equals(castOther.getCodAsignatura())))
				&& ((this.getCodTramo() == castOther.getCodTramo()) || (this
						.getCodTramo() != null
						&& castOther.getCodTramo() != null && this
						.getCodTramo().equals(castOther.getCodTramo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodOe() == null ? 0 : this.getCodOe().hashCode());
		result = 37 * result
				+ (getCodCurso() == null ? 0 : this.getCodCurso().hashCode());
		result = 37
				* result
				+ (getCodAsignatura() == null ? 0 : this.getCodAsignatura()
						.hashCode());
		result = 37 * result
				+ (getCodTramo() == null ? 0 : this.getCodTramo().hashCode());
		return result;
	}

}
