package clasesHibernate;

// Generated 18-nov-2015 12:47:59 by Hibernate Tools 3.4.0.CR1

/**
 * RepartoId generated by hbm2java
 */
public class RepartoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codOe;
	private String codCurso;
	private String codAsignatura;

	public RepartoId() {
	}

	public RepartoId(String codOe, String codCurso, String codAsignatura) {
		this.codOe = codOe;
		this.codCurso = codCurso;
		this.codAsignatura = codAsignatura;
	}

	public String getCodOe() {
		return this.codOe;
	}

	public void setCodOe(String codOe) {
		this.codOe = codOe;
	}

	public String getCodCurso() {
		return this.codCurso;
	}

	public void setCodCurso(String codCurso) {
		this.codCurso = codCurso;
	}

	public String getCodAsignatura() {
		return this.codAsignatura;
	}

	public void setCodAsignatura(String codAsignatura) {
		this.codAsignatura = codAsignatura;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepartoId))
			return false;
		RepartoId castOther = (RepartoId) other;

		return ((this.getCodOe() == castOther.getCodOe()) || (this.getCodOe() != null
				&& castOther.getCodOe() != null && this.getCodOe().equals(
				castOther.getCodOe())))
				&& ((this.getCodCurso() == castOther.getCodCurso()) || (this
						.getCodCurso() != null
						&& castOther.getCodCurso() != null && this
						.getCodCurso().equals(castOther.getCodCurso())))
				&& ((this.getCodAsignatura() == castOther.getCodAsignatura()) || (this
						.getCodAsignatura() != null
						&& castOther.getCodAsignatura() != null && this
						.getCodAsignatura()
						.equals(castOther.getCodAsignatura())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodOe() == null ? 0 : this.getCodOe().hashCode());
		result = 37 * result
				+ (getCodCurso() == null ? 0 : this.getCodCurso().hashCode());
		result = 37
				* result
				+ (getCodAsignatura() == null ? 0 : this.getCodAsignatura()
						.hashCode());
		return result;
	}

}
